// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOiEogCTQvcUL3Jcd9-C1Zz99NB90660',
    appId: '1:794645808744:web:09187285e148cb28a21ddd',
    messagingSenderId: '794645808744',
    projectId: 'court-booking-app-9d279',
    authDomain: 'court-booking-app-9d279.firebaseapp.com',
    storageBucket: 'court-booking-app-9d279.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOleYQ7JgWUqcjNb9wMmWSH8tS6lKc46w',
    appId: '1:794645808744:android:710d5ccbc12d1d1fa21ddd',
    messagingSenderId: '794645808744',
    projectId: 'court-booking-app-9d279',
    storageBucket: 'court-booking-app-9d279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabxF_OEtlDbRyw1s2MJ9fJZ9lFr05rzk',
    appId: '1:794645808744:ios:51f8e06ec7e3a45aa21ddd',
    messagingSenderId: '794645808744',
    projectId: 'court-booking-app-9d279',
    storageBucket: 'court-booking-app-9d279.firebasestorage.app',
    iosBundleId: 'com.example.courtBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabxF_OEtlDbRyw1s2MJ9fJZ9lFr05rzk',
    appId: '1:794645808744:ios:51f8e06ec7e3a45aa21ddd',
    messagingSenderId: '794645808744',
    projectId: 'court-booking-app-9d279',
    storageBucket: 'court-booking-app-9d279.firebasestorage.app',
    iosBundleId: 'com.example.courtBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSOiEogCTQvcUL3Jcd9-C1Zz99NB90660',
    appId: '1:794645808744:web:acf1feb3ec387b4ba21ddd',
    messagingSenderId: '794645808744',
    projectId: 'court-booking-app-9d279',
    authDomain: 'court-booking-app-9d279.firebaseapp.com',
    storageBucket: 'court-booking-app-9d279.firebasestorage.app',
  );
}
